### PR TITLE
Clock from external 16 MHz crystal

### PR DESCRIPTION
**Pull request by silverv**

### CODE REVIEW

**Review by pavel-kirienko — COMMENTED** [review]
@maksimdrachov please review

**Comment by maksimdrachov** [comment]
Input pins of external clock are `PA14` and `PA15`:

image

From the datasheet, those correspond to GCLKIO:

image

After `gclks_init`, GCLK register look as follows:

image

image

I would expect the `GCLK->GENCTRL->SRC` value to be `0x01`? Am I missing something?

**Comment by maksimdrachov** [comment]
image

After discussion with Pavel. 

The external clock is applied to the PLL, the PLL is then used at the clock source input.

**Comment by maksimdrachov** [comment]
image


image


Assuming the above is correct, I think this should be `0x2`.

image

Which of the 4 is the clock reference for `FDPLL96M`? I'm not sure.

**Comment by maksimdrachov** [comment]
## OSCCTRL

image

image

image


f_CKR = 16MHz
LDR = 2 (`DPLLRATIO->LDR = 0x2`)
LDRFRAC = 0 (`DPLLRATIO->LDRFRAC = 0x0`)
PRESC = 0 (`DLLPRESC->PRESC = 0x0`)

So DPLL output clock is: `16MHz * 3 = 48MHz`

**Comment by maksimdrachov** [comment]
image

Any reason why OSC48M clock needs to be enabled?

**Comment by maksimdrachov** [comment]
GCLK and MCLK seem to be correct. 

TODO:

- [x] Check with Pavel that 48MHz is the frequence we need (I don't know)
- [ ] Disable OSC48 (I think this was enabled by default, but I guess unnecessary)

After it can be merged. 👍  

- Make sure to configure pins in the `.dtsi` file (not this MR, but just a reminder as it is somewhat related to this)

**Review by maksimdrachov — APPROVED** [review]

**Comment by pavel-kirienko** [comment]
>Check with Pavel that 48MHz is the frequence we need (I don't know)

check :heavy_check_mark:

**Comment by silverv** [comment]
> GCLK and MCLK seem to be correct.
> 
> TODO:
> 
> * [x]  Check with Pavel that 48MHz is the frequence we need (I don't know)
> * [ ]  Disable OSC48 (I think this was enabled by default, but I guess unnecessary)
> 
> After it can be merged. +1
> 
> * Make sure to configure pins in the `.dtsi` file (not this MR, but just a reminder as it is somewhat related to this)

Let's disable the OSC48 in the next pull request, no need to put everything in a single pull request.

**Comment by pavel-kirienko** [comment]
@silverv please create an issue first when carrying incomplete tasks over from a pull request. This is so that we don't forget about these tasks later.

**Comment by silverv** [comment]
Exactly my thought but I don't see where it's possible to create issues. @pavel-kirienko

**Comment by silverv** [comment]
For now it is here: https://github.com/Zubax/epm_software/issues/92

**Comment by pavel-kirienko** [comment]
this is fine

**Pull request merged**
