### PR TITLE
Added CapVoltageProbe setup

### PR DESCRIPTION
**Pull request by maksimdrachov**

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
I suggest we move our custom patches into a separate branch dedicated to EPM, so that we don't have to maintain separate Zephyr forks per project that leverages this OS. Can you please change the merge target from `main` to `epm`?

**Comment by pavel-kirienko** [comment]
Or we merge it first and then rename `main` into `epm`?

**Comment by maksimdrachov** [comment]
Let's merge and I will take care of this.

**Review by pavel-kirienko — APPROVED** [review]
Okay. Maybe we should turn off the CI also, the diagnostics are annoying.

**Pull request merged**
